apps/cms/urls.py
#encoding: utf-8

from django.urls import path
from . import views

from django.shortcuts import reverse

# 设置app命名空间
app_name = 'cms'

urlpatterns = [
    path('',views.index,name='index'),
    path('write_news/',views.WriteNewsView.as_view(),name='write_news'),
    path('write_category/',views.news_category,name='news_category'),
    path('add_news_category/',views.add_news_category,name='add_news_category'),
    path('edit_news_category/',views.edit_news_category,name='edit_news_category'),
    path('delete_news_category/',views.delete_news_category,name='delete_news_category'),
    path('upload_file/',views.upload_file,name='upload_file'),

]

# url反转：通过视图函数反转为url
# rever("news:index")

apps/xfzauth/urls.py
#encoding: utf-8

from django.urls import path
from . import views

app_name = 'xfzauth'

urlpatterns = [
    path("login/",views.LoginView.as_view(),name='login'),
    path("register/",views.RegisterView.as_view(),name='register'),
    path("img_captcha/",views.img_captcha,name='img_captcha'),
    path("sms_captcha/",views.sms_captcha,name='sms_captcha'),
    path("logout/",views.logout_view,name='logout'),
]

xfz_project/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("",include("apps.news.urls")),
    path("account/",include("apps.xfzauth.urls")),
    path("cms/",include("apps.cms.urls")),
    path("news/",include("apps.news.urls")),
    path("payinfo/",include("apps.payinfo.urls")),
    path("course/",include("apps.course.urls")),
    path("ueditor/",include("apps.ueditor.urls")),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="//at.alicdn.com/t/font_681895_q7ptjm0r8n.css">
    <link rel="stylesheet" href="{% static 'css/base/front_base.css' %}">
<link rel="stylesheet" href="{% static 'css/base/side.css' %}">
    <script src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
    <script src="{% static 'js/xfzajax.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body>
    <header class="header">
        <nav class="nav">
            <h1 class="logo-box"></h1>
            <ul class="menu">
                <li class="active"><a href="#">创投资讯</a></li>
                <li><a href="#">创业课堂</a></li>
                <li><a href="#">付费资讯</a></li>
                <li><a href="#">搜索</a></li>
            </ul>
            <div class="auth-group">
                <span class="user-icon icon-person iconfont"></span>
                {% if user.is_authenticated %}
                    <a href="javascript:void(0);">{{ user.username }}</a>
                    <div class="user-more-box">
                        <i class="triangle"></i>
                        {% if user.is_staff %}
                            <a href="{% url 'cms:index' %}">管理系统</a>
                        {% endif %}
                        <a href="{% url 'xfzauth:logout' %}">退出登录</a>
                    </div>
                {% else %}
                    <a href="{% url 'xfzauth:login' %}">登录 /</a>
                    <a href="{% url 'xfzauth:register' %}">注册</a>
                {% endif %}
            </div>
        </nav>
    </header>
    {% block main %}{% endblock %}
    <footer class="footer">
        <div class="footer-1">
            <div class="footer-inner">
                <div class="logo-box"></div>
                <div class="detail-info-group">
                    <div class="top-group">
                        <ul class="links">
                            <li><a href="#">关于小饭桌</a></li>
                            <li><a href="#">创业课堂</a></li>
                            <li><a href="#">寻求报道</a></li>
                            <li><a href="#">创业礼包</a></li>
                        </ul>
                        <div class="about-us">
                            <span>关于我们：</span>
                            <span class="weixin">xfz008</span>
                            <span class="weibo">小饭桌创业课堂</span>
                        </div>
                    </div>
                    <div class="bottom-group">
                        <p class="address">地址：北京市朝阳区东三环北路38号院1号楼17层2001内1、16室</p>
                        <p class="contact">联系方式：400-810-1090（工作日10点-18点)</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-2">
            ©2017 北京子木投资顾问有限公司 京ICP备15051289号-1
        </div>
    </footer>
</body>
</html>

templates/base/side.html
<div class="course-group">
    <div class="top-group">
        <span class="title-group">在线课堂</span>
        <a href="#" class="more-group">更多</a>
    </div>
</div>
<div class="pay-info-group">
    <a href="#">
        <img src="http://www.xfz.cn/static/build/images/side-gift-banner.png" alt="">
    </a>
</div>
<div class="focus-group">
    <div class="title-group">关注小饭桌</div>
    <div class="website-group">
        <div class="left-group">
            <div class="item-group">
                <div class="logo-group zhihu-logo"></div>
                <div class="text-group">
                    <a href="#">小饭桌创业课堂</a>
                </div>
            </div>
            <div class="item-group">
                <div class="logo-group weibo-logo"></div>
                <div class="text-group">
                    <a href="#">小饭桌创业课堂</a>
                </div>
            </div>
            <div class="item-group">
                <div class="logo-group toutiao-logo"></div>
                <div class="text-group">
                    <a href="#">小饭桌</a>
                </div>
            </div>
        </div>
        <div class="right-group">
            <div class="qr-group"></div>
            <p class="text-group">扫码关注小饭桌微信公众平台xfz008</p>
        </div>
    </div>
</div>