apps/cms/urls.py
#encoding: utf-8

from django.urls import path
from . import views

from django.shortcuts import reverse

# 设置app命名空间
app_name = 'cms'

urlpatterns = [
    path('',views.index,name='index'),
    path('write_news/',views.WriteNewsView.as_view(),name='write_news'),
    path('write_category/',views.news_category,name='news_category'),
    path('add_news_category/',views.add_news_category,name='add_news_category'),
    path('edit_news_category/',views.edit_news_category,name='edit_news_category'),
    path('delete_news_category/',views.delete_news_category,name='delete_news_category'),
    path('upload_file/',views.upload_file,name='upload_file'),

]

# url反转：通过视图函数反转为url
# rever("news:index")

xfz_project/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("",include("apps.news.urls")),
    path("account/",include("apps.xfzauth.urls")),
    path("cms/",include("apps.cms.urls")),
    path("news/",include("apps.news.urls")),
    path("payinfo/",include("apps.payinfo.urls")),
    path("course/",include("apps.course.urls")),
    path("ueditor/",include("apps.ueditor.urls")),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

apps/cms/models.py
from django.db import models

# Create your models here.

apps/cms/forms.py
from apps.forms import FormMixin
from django import forms

from apps.news.models import *


class EditNewsCategoryForms(FormMixin,forms.Form):
    pk = forms.IntegerField(error_messages={'required':'必须传入参数'})
    name = forms.CharField(min_length=1,max_length=100)

class WriteNewsForms(forms.ModelForm,FormMixin):
    category = forms.IntegerField()
    class Meta:
        model = News
        fields = ('title','desc','thumbnail','content')
        error_messages = {
            'category':{
                'required':'必须传入分类的ID'
            },
        }

apps/cms/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.http import require_POST
from django.views.generic import View
from apps.news.models import *
from utils import restful
from .forms import *
from django.conf import settings
import os
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.

@staff_member_required(login_url='/')
def index(request):
    return render(request,'cms/index.html')

@method_decorator(login_required(login_url='/account/login/'),name='dispatch')
class WriteNewsView(View):
    def get(self,request):
        categories = NewsCategory.objects.all()
        return render(request,'cms/write_news.html',context={
            'categories':categories,
        })

    def post(self,request):
        form = WriteNewsForms(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = News.objects.filter(pk=category_id)
            News.objects.create(title=title,desc=desc,thumbnail=thumbnail,content=content,category=category,author=request.user)

            return restful.ok()
        else:
            return restful.params_error(message=form.get_error())

def news_category(request):
    categories = NewsCategory.objects.order_by('-id')
    return render(request,'cms/news_category.html',context={
        'categories':categories,
    })

@require_POST
def add_news_category(request):
    name = request.POST.get('name')
    exists= NewsCategory.objects.filter(name=name).exists()
    if not exists:
        NewsCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.params_error(message='该分类已经存在！')

@require_POST
def edit_news_category(request):
    form = EditNewsCategoryForms(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok()
        except:
            return restful.params_error(message='分类不存在')
    else:
        return restful.params_error(message=form.get_error())

@require_POST
def delete_news_category(request):
    pk = request.POST.get('pk')
    try:
        NewsCategory.objects.filter(pk=pk).delete()
        return restful.ok()
    except:
        return restful.params_error(message='该分类不存在')

@require_POST
def upload_file(request):
    file = request.FILES.get('upfile')
    name = file.name
    filepath = os.path.join(settings.MEDIA_ROOT,name)
    with open(filepath,'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    url = request.build_absolute_uri(settings.MEDIA_URL+name)
    return restful.result(data={"url":url})

templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} | 后台管理系统</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'sweetalert/xfzalert.js' %}"></script>
    <script src="{% static 'js/xfzajax.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>
{% block head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="index2.html" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg">后台管理系统</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=2361010523,1797416035&fm=27&gp=0.jpg" class="user-image" alt="User Image">
                            <span class="hidden-xs">小拓</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=2361010523,1797416035&fm=27&gp=0.jpg" class="img-circle" alt="User Image">

                                <p>
                                    小拓老师
                                    <small>Python web开发工程师</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <aside class="main-sidebar">
        <section class="sidebar">
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="搜索...">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
                </div>
            </form>
            <ul class="sidebar-menu" data-widget="tree">
                <li>
                    <a href="{% url 'cms:index' %}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
                <li class="header">新闻管理</li>
                <li>
                    <a href="{% url 'cms:write_news' %}">
                        <i class="fa fa-edit"></i>
                        <span>发布新闻</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'cms:news_category' %}">
                        <i class="fa fa-tag"></i>
                        <span>新闻分类</span>
                    </a>
                </li>
            </ul>
        </section>
    </aside>

    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}{% endblock %}
        </section>

        <section class="content">
            {% block content %}{% endblock %}
        </section>
    </div>

    <footer class="main-footer">
        大饭桌CMS后台管理系统
    </footer>
</div>
</body>
</html>

templates/cms/index.html
{% extends 'cms/base.html' %}

{% block content-header %}
    <h1>CMS后台管理系统首页</h1>
{% endblock %}

templates/cms/news_category.html
{% extends 'cms/base.html' %}

{% block title %}
    新闻分类
{% endblock %}

{% block head %}
    <script src="{% static 'js/news_category.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>新闻分类</h1>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header">
                <button id="add-btn" class="btn btn-primary pull-right">添加分类</button>
            </div>
            <div class="box-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>分类名称</th>
                            <th>新闻数量</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for category in categories %}
                            <tr data-pk="{{ category.pk }}" data-name="{{ category.name }}">
                                <td>{{ category.name }}</td>
                                <td>20</td>
                                <td>
                                    <button class="btn btn-warning btn-xs edit-btn">编辑</button>
                                    <button class="btn btn-danger btn-xs delete-btn">删除</button>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/cms/write_news.html
{% extends 'cms/base.html' %}

{% block title %}
    发布新闻
{% endblock %}

{% block head %}
    <script src="{% static 'js/write_news.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.config.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.all.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>发布新闻</h1>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <form action="" method="POST">
                <div class="box-body">
                    <div class="form-group">
                        <label for="title-form">标题</label>
                        <input type="text" name="title" id="title-form" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="desc-form">描述</label>
                        <input type="text" class="form-control" name="desc" id="desc-form">
                    </div>
                    <div class="form-group">
                        <label for="category-form">分类</label>

                        <select class="form-control" name="category" id="category-form">
                            {% for category in categories %}
                                <option value="{{ category.pk }}">{{ category.name }}</option>
                            {% endfor %}
                        </select>

                    </div>
                    <div class="form-group">
                        <label for="thumbnail-form">缩略图</label>
                        <div class="input-group">
                            <input type="text" name="thumbnail" class="form-control" id="thumbnail-form">
                            <span class="input-group-btn">
                                <label class="btn btn-default btn-file">
                                    上传图片<input hidden type="file" class="btn btn-default" id="upload-btn">
                                </label>
                            </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="content-form">内容</label>
                        <script id="editor" type="text/plain"></script>
                    </div>
                </div>
                <div class="box-footer">
                    <button class="btn btn-primary pull-right" id="submit-btn">发布</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}